// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageType.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf {

  /// <summary>Holder for reflection information generated from MessageType.proto</summary>
  public static partial class MessageTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for MessageType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFNZXNzYWdlVHlwZS5wcm90bxIIUHJvdG9idWYqKQoOQzJTTWVzc2FnZVR5",
            "cGUSCAoETm9uZRAAEg0KCVN0YXJ0R2FtZRABKjYKDlMyQ01lc3NhZ2VUeXBl",
            "EgkKBUVycm9yEAASDgoKR2FtZVJlc3VsdBABEgkKBURlYnVnEGNiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protobuf.C2SMessageType), typeof(global::Protobuf.S2CMessageType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum C2SMessageType {
    [pbr::OriginalName("None")] None = 0,
    [pbr::OriginalName("StartGame")] StartGame = 1,
  }

  public enum S2CMessageType {
    [pbr::OriginalName("Error")] Error = 0,
    [pbr::OriginalName("GameResult")] GameResult = 1,
    [pbr::OriginalName("Debug")] Debug = 99,
  }

  #endregion

}

#endregion Designer generated code
